### ISSUE TITLE
能补充个IMX219的配置吗

### ISSUE THREAD

**Issue by 63isOK** [HorizonRDK/hobot_mipi_cam#18]
IMX219_calibration.yaml

**Comment by zhuo511** [comment]
请问你这边使用的是文档中推荐的IMX219模块吗？

**Comment by 63isOK** [comment]
@zhuo511 是的.
在后面的测试中,发现使用F37的配置也能读取到IMX219设备的数据.

**Comment by zhuo511** [comment]
这个文件存放的是相机的内参，如果不需要该参数，可以不指定该配置。
